---

- name: Test for required variables
  ansible.builtin.include_tasks: assert.yml

- name: Load variables based on OS type
  ansible.builtin.include_tasks: vars.yml

- name: Include install.yml
  ansible.builtin.include_tasks: install.yml
  when: ansible_os_family != 'Windows'

- name: Include install-windows.yml
  ansible.builtin.include_tasks: install-windows.yml
  when: ansible_os_family == 'Windows'

- name: Include test.yml
  ansible.builtin.include_tasks: test.yml
  when: ansible_os_family != 'Windows'

- name: Include test.yml
  ansible.builtin.include_tasks: test-windows.yml
  when: ansible_os_family == 'Windows'
