---

- name: Test url
  when: rootca_test_url is defined and rootca_test_url | length > 0
  block:

    - name: Try connecting to test url
      ansible.builtin.uri:
        url: "{{ rootca_test_url }}"
        validate_certs: yes
        status_code: "{{ rootca_test_codes | default(omit) }}"
      changed_when: false
      ignore_errors: yes
      register: _rootca_test_url

    - name: Check if test failed
      ansible.builtin.debug:
        msg: Failed to connect to {{ rootca_test_url }}
      when: _rootca_test_url.failed

    - name: Fail play
      ansible.builtin.fail:
        msg: Stop is requested at failure of test
      when: rootca_test_fail | bool and _rootca_test_url.failed
