---

- block:

    - name: Try connecting to test url
      uri:
        url: "{{ rootca_test_url }}"
        validate_certs: yes
      changed_when: false
      register: _rootca_test_url

    - name: Failed to connect to {{ rootca_test_url }}
      debug:
        msg: Failed to connect to {{ rootca_test_url }}
      when: _rootca_test_url.rc > 0

    - name: Fail play
      fail:
        msg: Stop is requested at failure of test
      when: rootca_test_fail|bool

  when: rootca_test_url is defined and rootca_test_url|length > 0
