---

- name: Converge
  hosts: all
  vars:
    rootca_certificates: ['tests/root1.crt', 'tests/root2.pem']
  tasks:
    - name: Include role 'ansible-role-rootca'
      include_role:
        name: ansible-role-rootca
