---

- name: Converge
  hosts: all
  become: "{{ molecule['converge']['become'] | default('yes') }}"
  vars:
    rootca_certificates: ['tests/root1.crt', 'tests/root2.pem']
  tasks:
    - name: Include role 'ansible-role-rootca'
      ansible.builtin.include_role:
        name: ansible-role-rootca
